runtime: go
api_version: go1.9

skip_files:
  - ^(.*/)?.*\.DS_Store$

handlers:
    - url: /api/admin/.*
      secure: always
      login: admin
      script: _go_app

    - url: /api/.*
      secure: always
      login: required
      script: _go_app
