runtime: go
api_version: go1.9

skip_files:
  - ^(.*/)?.*\.DS_Store$
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$

handlers:
    - url: /api/admin/.*
      secure: always
      login: admin
      script: _go_app

    - url: /api/tasks/.*
      secure: always
      login: admin
      script: _go_app

    - url: /api/users/.*
      secure: always
      login: required
      script: _go_app

    - url: /api/.*
      secure: always
      login: required
      script: _go_app
